In [1]:
import numpy as np
from scipy.linalg import eig
from scipy.linalg import svd

def compute_svd(a):
    U, s, Vh = svd(a, full_matrices=False)
    print(a)
    print(U)
    print(s)
    print(Vh)

A = np.array([[2, -4], [-1, -1]])
B = np.array([[3, 1], [1, 3]])
C = np.dot(A, B)
D = np.dot(B, A)
c = np.array([[3,1],[1, 3],[2,-4],[-1,-1]])

In [2]:
w, vl, vr = eig(C,  left=True)
print(C)
print(w)
print(vr)
print(vl)

[[  2 -10]
 [ -4  -4]]
[ 6.+0.j -8.+0.j]
[[ 0.92847669  0.70710678]
 [-0.37139068  0.70710678]]
[[ 0.70710678  0.37139068]
 [-0.70710678  0.92847669]]


In [3]:
w, vl, vr = eig(D,  left=True)
print(D)
print(w)
print(vr)
print(vl)

[[  5 -13]
 [ -1  -7]]
[ 6.+0.j -8.+0.j]
[[ 0.99705449  0.70710678]
 [-0.0766965   0.70710678]]
[[ 0.70710678  0.0766965 ]
 [-0.70710678  0.99705449]]


In [4]:
compute_svd(A)

[[ 2 -4]
 [-1 -1]]
[[ 0.99402894  0.10911677]
 [ 0.10911677 -0.99402894]]
[ 4.49661478  1.33433712]
[[ 0.41785681 -0.9085129 ]
 [ 0.9085129   0.41785681]]


In [5]:
compute_svd(np.dot(A,A))

[[ 8 -4]
 [-1  5]]
[[-0.92036286  0.39106549]
 [ 0.39106549  0.92036286]]
[ 9.58630798  3.75535608]
[[-0.80885867  0.5880031 ]
 [ 0.5880031   0.80885867]]


In [6]:
compute_svd(np.dot(A,B))

[[  2 -10]
 [ -4  -4]]
[[ 0.9347217   0.35538056]
 [ 0.35538056 -0.9347217 ]]
[ 10.77805077   4.45349545]
[[ 0.04155864 -0.99913607]
 [ 0.99913607  0.04155864]]


In [7]:
compute_svd(np.dot(B,A))

[[  5 -13]
 [ -1  -7]]
[[ 0.90607303  0.42312134]
 [ 0.42312134 -0.90607303]]
[ 15.30230699   3.13678193]
[[ 0.26840683 -0.96330565]
 [ 0.96330565  0.26840683]]


In [8]:
compute_svd(c)

[[ 3  1]
 [ 1  3]
 [ 2 -4]
 [-1 -1]]
[[-0.14395373  0.79545124]
 [-0.5586541   0.32209809]
 [ 0.79770252  0.4306424 ]
 [ 0.17565196 -0.27938733]]
[ 5.20411016  3.86228397]
[[ 0.08248053 -0.99659268]
 [ 0.99659268  0.08248053]]
