In [1]:
##  6 System Identifcation by ordinary least squares regression, part(a)
from scipy.io import loadmat
import numpy as np
from numpy.linalg import inv

In [2]:
a = loadmat('hw01-data/system-identification/a.mat')
x = np.transpose(a['x'])
u = np.transpose(a['u'])

X = np.hstack((x[:29, :], u[:29, :]))
y =  x[1:30, :]

XT = np.transpose(X)
w = np.dot(inv(XT @ X) @ XT, y)

print(w)

[[ 0.97755214]
 [-0.08775322]]


In [3]:
##  6 System Identifcation by ordinary least squares regression, part(b)

b = loadmat('hw01-data/system-identification/b.mat')
u = b['u']
x = b['x']
u = u.reshape(u.shape[0:2])
x = x.reshape(x.shape[0:2])
n = u.shape[0]

Y = x[1:n, :].transpose()
X = np.vstack((x[0:n-1, :].transpose(), u[0:n-1, :].transpose()))
XT = X.transpose()
W = Y @ XT @ inv(X @ XT)
A = W[:, 0:3]
B = W[:, 3:6]
print(A)
print('\n')
print(B)

[[ 0.15207406  0.93480864 -0.00110243]
 [ 0.03893567  0.30958727  0.87436511]
 [-0.52552959  0.0540906  -0.47026217]]


[[ 0.04894161  0.20568264 -0.37090438]
 [-0.04524735 -0.92861546  0.12756569]
 [ 0.91096923 -0.47124981 -0.84222314]]


In [4]:
##  6 System Identifcation by ordinary least squares regression, part(c)

train = loadmat('hw01-data/system-identification/train.mat')
x = train['x'].transpose()
xd = train['xd'].transpose()
xdd = train['xdd'].transpose()
xp = train['xp'].transpose()
xdp = train['xdp'].transpose()
n = x.shape[0]

X = np.hstack((x, xd, xp, xdp, np.ones((n, 1))))
y = xdd
XT = X.transpose()
w = np.dot(inv(XT @ X) @ XT, y)
print(w)

[[-0.01152121]
 [-0.31779341]
 [ 0.01128933]
 [ 0.27535824]
 [-0.88293502]]
